{"name": "test_load_testing", "status": "failed", "statusDetails": {"message": "AssertionError: Нагрузочное тестирование завершилось с ошибкой\nassert 2 == 0", "trace": "home_setup = <pages.home_page.HomePage object at 0x000002652676EE10>\n\n    @allure.feature(\"Производительность под нагрузкой\")\n    @allure.story(\"Нагрузочное тестирование\")\n    def test_load_testing(home_setup):\n        result = os.system(\"locust -f locustfile.py --headless -u 100 -r 10 -t 1m\")\n>       assert result == 0, \"Нагрузочное тестирование завершилось с ошибкой\"\nE       AssertionError: Нагрузочное тестирование завершилось с ошибкой\nE       assert 2 == 0\n\ntests\\test_perfomance.py:47: AssertionError"}, "attachments": [{"name": "stderr", "source": "393651aa-1355-477f-b91f-0a322f23296a-attachment.txt", "type": "text/plain"}], "start": 1739122258432, "stop": 1739122860662, "uuid": "1861f7b8-f5ae-49a8-8c8c-65132e5aa698", "historyId": "b16bcb8f167273202388d59d24ae8cbe", "testCaseId": "b16bcb8f167273202388d59d24ae8cbe", "fullName": "tests.test_perfomance#test_load_testing", "labels": [{"name": "feature", "value": "Производительность под нагрузкой"}, {"name": "story", "value": "Нагрузочное тестирование"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_perfomance"}, {"name": "host", "value": "kachanneee"}, {"name": "thread", "value": "13484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_perfomance"}]}