{"name": "test_load_testing", "status": "failed", "statusDetails": {"message": "AssertionError: Нагрузочное тестирование завершилось с ошибкой\nassert 2 == 0", "trace": "home_setup = <pages.home_page.HomePage object at 0x000002571A12AC90>\n\n    @allure.feature(\"Производительность под нагрузкой\")\n    @allure.story(\"Нагрузочное тестирование\")\n    def test_load_testing(home_setup):\n        result = os.system(\"locust -f locustfile.py --headless -u 100 -r 10 -t 1m\")\n>       assert result == 0, \"Нагрузочное тестирование завершилось с ошибкой\"\nE       AssertionError: Нагрузочное тестирование завершилось с ошибкой\nE       assert 2 == 0\n\ntests\\test_perfomance.py:46: AssertionError"}, "attachments": [{"name": "stderr", "source": "e47c95a1-2e7f-494a-88c4-7799068004bc-attachment.txt", "type": "text/plain"}], "start": 1739100805877, "stop": 1739101410380, "uuid": "0a7e4d23-7369-4787-ae60-a1725e2a5237", "historyId": "b16bcb8f167273202388d59d24ae8cbe", "testCaseId": "b16bcb8f167273202388d59d24ae8cbe", "fullName": "tests.test_perfomance#test_load_testing", "labels": [{"name": "story", "value": "Нагрузочное тестирование"}, {"name": "feature", "value": "Производительность под нагрузкой"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_perfomance"}, {"name": "host", "value": "kachanneee"}, {"name": "thread", "value": "19572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_perfomance"}]}