{"name": "test_load_testing", "status": "failed", "statusDetails": {"message": "AssertionError: Нагрузочное тестирование завершилось с ошибкой\nassert 2 == 0", "trace": "home_setup = <pages.home_page.HomePage object at 0x0000014E080CDF10>\n\n    @allure.feature(\"Производительность под нагрузкой\")\n    def test_load_testing(home_setup):\n        result = os.system(\"locust -f locustfile.py --headless -u 100 -r 10 -t 1m\")\n>       assert result == 0, \"Нагрузочное тестирование завершилось с ошибкой\"\nE       AssertionError: Нагрузочное тестирование завершилось с ошибкой\nE       assert 2 == 0\n\ntests\\test_perfomance.py:44: AssertionError"}, "attachments": [{"name": "stderr", "source": "c52b91c0-e3c1-4b1b-9301-fbed967f7ec2-attachment.txt", "type": "text/plain"}], "start": 1739039817996, "stop": 1739040421198, "uuid": "ea50861e-6685-41a3-a4d9-39a041e71195", "historyId": "b16bcb8f167273202388d59d24ae8cbe", "testCaseId": "b16bcb8f167273202388d59d24ae8cbe", "fullName": "tests.test_perfomance#test_load_testing", "labels": [{"name": "feature", "value": "Производительность под нагрузкой"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_perfomance"}, {"name": "host", "value": "kachanneee"}, {"name": "thread", "value": "36424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_perfomance"}]}